notify_webhook: ""
cpu_limit: 90
mem_limit: 90
serv_url: ""

# unit: day
lifecycle:
  container_running: 7
  release: 1
  pkg: 7
  image_created: 1

wechat:
  corp_id: ""
  app_secret: ""
  department_id: 1
