[package]
name = "visor-serv"
version = "0.1.0"
edition = "2021"
authors = ["K8sCat <k8scat@gmail.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
shiplift = "0.7"
env_logger = "0.8.4"
